---
title: "CART Complexity Tuning"
author: "Albert Y. Kim"
date: "2017-10-30"
output: html_document
runtime: shiny
---

The source `.Rmd` file for this Shiny app can be found [here]().

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rpart)
iris <- iris %>%
  as_tibble() %>%
  # Add ID column:
  mutate(ID = 1:n()) %>% 
  select(ID, Species, Sepal.Length, Sepal.Width)
model_formula <- as.formula(Species ~ Sepal.Length + Sepal.Width)
```



## Tuning parameter

Recall for a given tuning parameter $\alpha$, we want to find the subtree that 
minimizes the following:

$$
\sum_{m=1}^{|T|}\sum_{x_i \in R_m} \left(y_i - \widehat{y}_{R_m}\right)^2 + \alpha |T|
$$

Let's set the tuning parameter $\alpha$ using the slider below, which is defined
as `cp` in `rpart.control()`, and plot resulting tree. For example using
`cp=0.01`, which is the default value (see `?rpart.control`).

```{r, eval=FALSE}
# Define tree
tree_parameters <- rpart.control(cp=0.01)
model_CART <- rpart(model_formula, data = iris, control=tree_parameters)

# Plot
plot(model_CART, margin=0.25)
text(model_CART, use.n = TRUE)
title("Predicting iris species using sepal length & width")
box()
```

```{r, echo=FALSE}
inputPanel(
  sliderInput("cp", label = "Tuning parameter alpha:", min = 0, max = 0.5, value = 0.01, step = 0.001)
)
```


```{r, echo=FALSE}
renderPlot({
  # Create tree
  tree_parameters <- rpart.control(cp=input$cp)
  model_CART <- rpart(model_formula, data = iris, control=tree_parameters)
  
  # Plot
  plot(model_CART, margin=0.25)
  text(model_CART, use.n = TRUE)
  title("Predicting iris species using sepal length & width")
  box()
}, height=900/2, width=1600/2)
```
